name: my test ci workflow

on:
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: 
      - master

jobs:
  run:
    uses: ./.github/workflows/ci-template.yml
    with:
      first_parameter: "Hello"
      second_parameter: "World"



