name: workflow-template

on: 
  workflow_call:
    inputs:
      first_parameter:
        type: string
        required: true
      second_parameter:
        type: string
        required: true

jobs:
  output-text:
    uses: ChristianPejrup/github-action-templates-playground/.github/workflows/template1and2.yml@v0.4.0
    secrets: inherit
    with:
      first_parameter: ${{ inputs.first_parameter }}
      second_parameter: ${{ inputs.second_parameter }}