name: .NET Core CI

on:
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: 
      - master

env:
  CONFIGURATION: Release
  CODECOVERAGE_DIRECTORY: ./coverage-reports
  CODECOVERAGE_REPORT: coverage.opencover.xml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Test with coverage
      run: |
        coverlet ./tests/UnitTests/bin/${{ env.CONFIGURATION }}/net8.0/UnitTests.dll --target "dotnet" --targetargs "test --configuration ${{ env.CONFIGURATION }} ./tests/UnitTests --no-build" --format opencover --output "${{ env.CODECOVERAGE_DIRECTORY }}/${{ env.CODECOVERAGE_REPORT }}"
      shell: pwsh
    
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate report
      run: reportgenerator "-reports:${{ env.CODECOVERAGE_DIRECTORY }}/${{ env.CODECOVERAGE_REPORT }}" "-targetdir:${{ env.CODECOVERAGE_DIRECTORY }}" "-reporttypes:Html"

    - name: Publish report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ env.CODECOVERAGE_DIRECTORY }}