name: .NET Core CI

on:
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Test with coverage
      run: coverlet ./tests/ --target "dotnet" --targetargs "test --no-build" --format opencover --output "./coverage-reports/"
    
    - name: Test with coverage
      run: coverlet ./tests/UnitTests/bin/Release/netcoreapp3.1/UnitTests.dll --target "dotnet" --targetargs "test --no-build" --format opencover --output "./coverage-reports/"

    - name: Generate report
      run: dotnet reportgenerator "-reports:coverage.opencover.xml" "-targetdir:coveragereport" "-reporttypes:Html"

    - name: Publish report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coveragereport/