name: my test ci workflow

on:
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: 
      - master

jobs:
  output-text:
    uses: ChristianPejrup/github-action-templates-playground/.github/workflows/template1and2.yml@v0.4.0
    secrets: inherit
    with:
      first_parameter: "Hello"
      second_parameter: "World"



